// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using OrionTestAPI.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace OrionTestAPI.Data
{
    public partial interface IOrionTestAPIContextProcedures
    {
        Task<int> AddAddressToClientAsync(int? ClientId, string Address, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> AddClientAsync(string Name, DateTime? EntryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteAddressToClientAsync(int? AddressClientId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteClientAsync(int? ClientId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateAddressToClientAsync(int? AddressClientId, string Address, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateClientAsync(int? ClientId, string Name, DateTime? EntryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
