// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrionTestAPI.Models
{
    public partial class AddressClient
    {
        public int AddressClientId { get; set; }
        public int ClientId { get; set; }
        public string Address { get; set; }

        public virtual Client Client { get; set; }
    }
}