// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrionTestAPI.Models
{
    public partial class Client
    {
        public Client()
        {
            AddressClients = new HashSet<AddressClient>();
        }

        public int ClientId { get; set; }
        public string Name { get; set; }
        public DateTime? EntryDate { get; set; }

        public virtual ICollection<AddressClient> AddressClients { get; set; }
    }
}